#!/usr/bin/env node

/**
* Snapshot
*
* Usage example:
*
* $ snapshot remote  
* $ snapshot remote save
* $ snapshot local save
* $ snapshot save
*
*/

var args = require('./snapshot-args')
var options = args()

if(options){
  var snapshot = require('./organization-disk-usage')
  var mongo = require('./organization-disk-usage/node_modules/mongoskin')

  var start = process.hrtime();

  var elapsedTime = function(note){
    var precision = 3;
    var elapsed = process.hrtime(start)[1] / 1000000; 
    console.log(process.hrtime(start)[0] + " s, " + elapsed.toFixed(precision) + " ms - " + note); 
    start = process.hrtime(); 
  }

  console.log(options)
  snapshot(options, function(err, res){
    if(err) throw err
    console.log(res)
    console.log("len: " + res.length)
    elapsedTime("Retrieved")
  })
}