#!/usr/bin/env node
var prompt = require("prompt");
var settings = require(__dirname + "/../../settings");

var app = {
  db: function(modelName) {
    return settings.model(settings.db, modelName);
  }
  , ObjectID: settings.ObjectID
  , validator: settings.validator
}

var user = require(__dirname + "/../../sinergis/models/user")(app);

settings.db.open(function(){
  console.log("database is "  + (settings.db.serverConfig.isConnected() ? "connected" : "not connected"));
  console.log("database name: ", settings.db.databaseName);

  console.log("!!!!!!!!!!");

  var schema = {
    properties : {
      username: {
        pattern: /^[a-zA-Z0-9-._]{3,100}$/,
        message: "Invalid username",
        required: true
      },
      password: {
        pattern: /.{6,20}/,
        message: "Invalid password. Length 6 - 20",
        required: false,
        hidden: true
      },
      confirm: {
        pattern: /.{6,20}/,
        message: "Invalid password. Length 6 - 20",
        required: true,
        hidden: true
      }
    }
  };

  prompt.start();

  prompt.get(schema, function (err, result) {
    if (!result) {
      console.log("bye!");
      process.exit();
    }

    if (result.password != result.confirm) {
      console.log("Error changing password");
      process.exit();
    }

    user.changePassword(result.username, result.password, function(v) {
      if (v.hasErrors() == false) {
      
        console.log("changed ->", result.username, ":", result.password);
        process.exit();
      
      } else {
        console.log(v.errors);
        process.exit();
      }
    });
  });
}); 

